### ISSUE TITLE
[Bug]: When initiating a database permission application again, the name is not the same as when initiating a database permission application again

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1793]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/2c241f37-ca7d-408e-be87-a8434d39ba55)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/700f3bbe-ac30-4178-ac34-382a36eea534)

### How can we reproduce it (as minimally and precisely as possible)?

Initiate another application for library permissions

**Comment by HSunboy** [comment]
Fixed In Commit [9cbb7d5bad2e32d15014951f4d0d9d2e688a45af](https://github.com/oceanbase/odc-client/commit/9cbb7d5bad2e32d15014951f4d0d9d2e688a45af)
            ------
            咏和
            Mon Mar 11 10:55:33 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/05b6b0ce-a810-469b-b72d-349fe661ef93)

Problem not fixed

**Comment by bluesky-xyh** [comment]
It is the same as PD confirmed, and the new title is the same as the new title. The only difference is that the data is echoed.
