### ISSUE TITLE
[Bug]: Setting the shortcut key to Ctrl+enter does not take effect when executed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2312]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/8e4f662d-5f6b-450e-b0cb-22c59680f1d7)

### What did you expect to happen?

Executed two SQL statements

### How can we reproduce it (as minimally and precisely as possible)?

1. Set the shortcut key to ctrl+enter
2. Execute SQL through shortcut key

**Comment by HSunboy** [comment]
Fixed In Commit [d31cb481dabafa8c16da72627922b725d8f47a35](https://github.com/oceanbase/odc-client/commit/d31cb481dabafa8c16da72627922b725d8f47a35)
            ------
            xiaokang
            Wed May 29 13:56:54 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/ad6324ff-43d7-45b1-987c-7a089f957fae)

Problem not fixed

**Comment by HSunboy** [comment]
Fixed In Commit [ef800f681bb258cd7f17f21fc078adc213beb5e1](https://github.com/oceanbase/odc-client/commit/ef800f681bb258cd7f17f21fc078adc213beb5e1)
            ------
            xiaokang
            Tue Jun 4 16:42:36 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/382f4faa-35a3-4b03-abd9-013e4f2cee6e)

pass
