### ISSUE TITLE
[Bug]: When a multi-database change task is delivered, the libraries that users do not have permission for should be grey

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2567]
### ODC version

ODC 4.3.0

### OB version

No related.

### What happened?

When a multi-database change task is delivered, the libraries that users do not have permission for should be grey
![image](https://github.com/oceanbase/odc/assets/46598871/f1ec7e2c-8e76-40e2-a492-609e2a0f9298)

### What did you expect to happen?

Should be gray and hover prompt no permissions.

### How can we reproduce it (as minimally and precisely as possible)?

Deliver a multi-database change task and select a database that has no permission.

**Comment by HSunboy** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)
            ------
            陈朝俊
            Tue Jun 4 20:45:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/d3b84d49-7abe-40ee-8688-d863b48368b6)

The problem still exists

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/474657ea-c2f0-445e-8a61-d95b686f0a46)
pass
