### ISSUE TITLE
[Bug]: There is no SQL in the execution plan

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2814]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/6d3459c3-43ec-4d54-a86b-2be4f1b5c9b6)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/f29031f4-825e-4704-a78f-4eb8b2965e6a)

### How can we reproduce it (as minimally and precisely as possible)?

After entering SQL, click on the execution plan

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/51d12a0e-8d28-4eee-99dd-169772325ca7)

Problem not fixed

**Comment by HSunboy** [comment]
Fixed In Commit [d7addf8113ff4e6e6fd30003509e26d4d8ebac08](https://github.com/oceanbase/odc-client/commit/d7addf8113ff4e6e6fd30003509e26d4d8ebac08)
            ------
            畅晚
            Wed Jul 10 13:58:11 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/048c5da5-9a19-4a12-b1e6-7cd1ffa1aff6)
pass
