### ISSUE TITLE
[Bug]: The length of the operator node sorting tab is inconsistent with the design draft

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2827]
### ODC version

odc431

### OB version

ob424

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/66b2f495-1b3a-453f-94b8-b82065bf348c)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/7f1c62de-2f20-40f8-a0f1-68735448477c)

### How can we reproduce it (as minimally and precisely as possible)?

Execute SQL, click on the execution profile, select the operator node, and perform a dropdown sorting

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/7424cd5e-47ec-4730-9e73-35476e69013b)

The problem still exists after selecting the option below
