### ISSUE TITLE
[Bug]: Unable to view full link diagnosis when OB version is 43x

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2833]
### ODC version

odc431

### OB version

ob43x

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/3cf34535-2913-4c8a-a16c-09e50613995e)

### What did you expect to happen?

Full link diagnosis should be able to view

### How can we reproduce it (as minimally and precisely as possible)?

Execute SQL on version ob43x, click on execution profile, and click on full link diagnosis

**Comment by HSunboy** [comment]
Fixed In Commit [48b0a9c5867f163404fe6f4e9dff480c9c247272](https://github.com/oceanbase/odc-client/commit/48b0a9c5867f163404fe6f4e9dff480c9c247272)
            ------
            畅晚
            Fri Jul 12 17:33:57 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/a55c7f45-7994-4e21-b2e8-9f6da0615154)

Full link diagnosis still cannot be viewed

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/eff5c9c7-b27a-48a2-ae08-69c6bf2d66a4)

pass
