### ISSUE TITLE
[Bug]: There are spaces before and after the names and parameters of MySQL functions and stored procedure formats

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2867]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/a086e64b-b53b-4007-b924-56dfb3409c45)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/a987c15b-4193-42d6-9a7e-27f5692aa720)

### How can we reproduce it (as minimally and precisely as possible)?

Format function after creation

**Comment by HSunboy** [comment]
fixed in dev-4.3.1

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/600633b3-55f2-40c3-9b15-2ff0ed69d4db)
The problem still exists

**Comment by HSunboy** [comment]
Fixed In Commit [fd338ebd8596f86f9e58ca2a98f817d6702d9a4a](https://github.com/oceanbase/odc-client/commit/fd338ebd8596f86f9e58ca2a98f817d6702d9a4a)
            ------
            xiaokang
            Mon Jul 8 10:32:45 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/26e538de-0857-4996-861b-6276afaa1e19)

pass
