### ISSUE TITLE
[Bug]: The database for applying for library permissions is not fully displayed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2892]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/3623eb5f-54af-4627-97c1-926ced5de4e7)

### What did you expect to happen?

Display completely

### How can we reproduce it (as minimally and precisely as possible)?

Select a project after entering the application library permission

**Comment by HSunboy** [comment]
Fixed In Commit [4ea3890e386e41f9ca5742fd5069bef6392b0370](https://github.com/oceanbase/odc-client/commit/4ea3890e386e41f9ca5742fd5069bef6392b0370)
            ------
            畅晚
            Mon Jul 29 10:20:18 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/8c36eef4-6b4f-4414-b0fd-0fcecba11d12)

The problem still exists

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/f420f24f-502e-4161-a749-c7141843922a)

pass
