### ISSUE TITLE
[Bug]: When the bit type field is empty, the PG database is archived to ob and then cleaned up and reports a null pointer

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3188]
### ODC version

ODC432

### OB version

pg9
ob mysql422

### What happened?

After the bit type pg database is archived to ob and cleaned up, a null pointer is reported
![image](https://github.com/user-attachments/assets/aa19bc2c-586f-42b1-a8f6-ad47e6303775)
![image](https://github.com/user-attachments/assets/46d85db9-8e49-4169-abc1-d42845a5f657)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

```
CREATE TABLE public.test_4 (
	col1 int4 NOT NULL,
	col2 numeric(10, 2) NULL,
	col3 numeric(10, 2) NULL,
	col4 bit(8) NULL,
	CONSTRAINT test_4_pkey PRIMARY KEY (col1)
);
```

```
INSERT INTO public.test_4 (col1,col2,col3,col4) VALUES
	 (1,NULL,NULL,NULL);

```

**Comment by kiko-art** [comment]
fixed

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/bbf6298a-510c-4a31-828a-86e94f2b361e)
The problem still exists
