### ISSUE TITLE
[Bug]: The details of the database permission application ticket are inconsistent with those displayed on the UED

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3548]
### ODC version

4.3.2

### OB version

no related

### What happened?

The details of the database permission application ticket are inconsistent with those displayed on the UED
![image](https://github.com/user-attachments/assets/3ed91953-b2ea-45c0-a1bd-155c5a77b663)
![image](https://github.com/user-attachments/assets/4fd0f1f8-a9a8-4aa0-9596-dddcb4745310)

### What did you expect to happen?

The details of the database permission ticket should be the same as those displayed in the UED

### How can we reproduce it (as minimally and precisely as possible)?

Initiate a database permission application ticket to view the ticket details

**Comment by HSunboy** [comment]
Fixed In Commit [9ec5ef705eea3bacdc1619f6bb9cd43dfe261219](https://github.com/oceanbase/odc-client/commit/9ec5ef705eea3bacdc1619f6bb9cd43dfe261219)
            ------
            畅晚
            Wed Sep 25 16:02:09 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/03c57b01-fdbc-42ec-af00-f47a2d6b2f30)
The problem still exists

**Comment by HSunboy** [comment]
Fixed In Commit [65b92a945308b43628795d6f1a651ebdbfda03e1](https://github.com/oceanbase/odc-client/commit/65b92a945308b43628795d6f1a651ebdbfda03e1)
            ------
            畅晚
            Thu Sep 26 15:23:52 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/f10b1b45-de42-4fad-a218-c2f04fe8ae07)
pass
