### ISSUE TITLE
[Bug]: When creating an index, it will be displayed as unavailable with no unavailable markers

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#585]
### ODC version

odc422

### OB version

ob324

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/d10d5b70-8835-4aa3-a473-21f008ea409d)

### What did you expect to happen?

Unavailable index has an unavailable identifier

### How can we reproduce it (as minimally and precisely as possible)?

Viewing Index Status When Creating an Index

**Comment by HSunboy** [comment]
fixed in dev-4.2.2

**Comment by sl01388797** [comment]
Problem not fixed
![image](https://github.com/oceanbase/odc/assets/143492234/35ccd4af-9e3f-4483-acce-3742504dc7d0)

**Comment by HSunboy** [comment]
Fixed In Commit [a98ee01affe935ca6ee50ee2eeb508c2d7c0f72c](https://github.com/oceanbase/odc-client/commit/a98ee01affe935ca6ee50ee2eeb508c2d7c0f72c)
            ------
            晓康
            Mon Oct 30 11:25:32 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/f0a5c809-dee1-48fb-827d-8bb0f609ec84)
pass
